= Sample Application that demonstrates AIBatchTools libaries

The purpose of this project is to demonstrate the usage of the TikaItemReader, VectorStoreItemReader and their builders.

== Requirements:

* Java 17 or Above

== Classes:

* MongoBatchVectorApplication - The boot application for this project.
* MongoBatchVectorConfiguration - Provides the configuration for the batch job.

== Build:

Before building be sure to pull and build the https://github.com/cppwfs/aibatchtools[aibatchtools] project based on its https://github.com/cppwfs/aibatchtools/blob/main/README.adoc[README] instructions
[source,shell]
----
mvn clean package -DskipTests
----

== Before Running the App
You will need to setup up a `Mongo Atlas` service with a database prior to running the application.  Instructions can be found https://www.mongodb.com/docs/atlas/getting-started/[here].

== Run:

* Since this project is creating its embeddings for OpenAI you need to have the `SPRING_AI_OPENAI_API_KEY` set.
* spring_data_mongodb_uri will need be set with the URL provided by `Mongo Atlas`.

[source,shell]
----
export SPRING_AI_OPENAI_API_KEY=<yourkey>
export spring_data_mongodb_uri=<URI>

java -jar target/mongobatchvector-0.0.1-SNAPSHOT.jar
----
